const enum MutationTypes {
    SET_FIELDS = 'SET_FIELDS',
    SET_FIELDS_ERROR = 'SET_FIELDS_ERROR',
    SET_FIELDS_COUNT = 'SET_FIELDS_COUNT',
    CHANGE_FIELDS_PAGE = 'CHANGE_FIELDS_PAGE',
    CHANGE_FIELDS_LOADING = 'CHANGE_FIELDS_LOADING',
    SET_FIELD_ASSOCIATIONS = 'SET_FIELD_ASSOCIATIONS'
}
export default MutationTypes