const enum MutationTypes {
    SET_REQUESTS = 'SET_REQUESTS',
    SET_REQUEST = 'SET_REQUEST',
    SET_REQUESTS_ERROR = 'SET_REQUESTS_ERROR',
    SET_REQUESTS_COUNT = 'SET_REQUESTS_COUNT',
    CHANGE_REQUESTS_PAGE = 'CHANGE_REQUESTS_PAGE',
    CHANGE_REQUESTS_LOADING = 'CHANGE_REQUESTS_LOADING',
}
export default MutationTypes